# Generated by Django 5.0.4 on 2024-04-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Spotify',
            fields=[
                ('usuario', models.CharField(default='1', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('token_acesso', models.CharField(max_length=150)),
                ('token_novo', models.CharField(max_length=150)),
                ('data_token', models.DateTimeField(auto_now_add=True)),
                ('expires_in', models.DateTimeField()),
            ],
        ),
    ]
