# Generated by Django 5.0.4 on 2024-04-04 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spokefyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe_Pkmn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=20)),
                ('tamanho_equipe', models.IntegerField(default=0)),
                ('pkmn_list', models.JSONField(default=dict)),
                ('playlist', models.CharField(default=None, max_length=20, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spokefyapp.usuario_spotify')),
            ],
        ),
    ]
